In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [4]:
df.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

In [9]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [21]:
df[
    df['Make'] == 'BMW'
].mean()

Year                 2014.347305
Engine HP             326.907186
Engine Cylinders        5.958084
Number of Doors         3.161677
highway MPG            29.245509
city mpg               20.739521
Popularity           3916.000000
MSRP                61546.763473
dtype: float64

In [19]:
df2.mean()

Year                 2014.347305
Engine HP             326.907186
Engine Cylinders        5.958084
Number of Doors         3.161677
highway MPG            29.245509
city mpg               20.739521
Popularity           3916.000000
MSRP                61546.763473
dtype: float64

In [33]:
df3 = df[['Year', 'Engine HP']]

In [38]:
df3[
    df['Year'] >= 2015
].isnull().sum()

Year          0
Engine HP    51
dtype: int64

In [39]:
df3.describe()

Year    Engine HP
count  11914.000000  11845.00000
mean    2010.384338    249.38607
std        7.579740    109.19187
min     1990.000000     55.00000
25%     2007.000000    170.00000
50%     2015.000000    227.00000
75%     2016.000000    300.00000
max     2017.000000   1001.00000

In [46]:
df4 = df3.fillna(df3.mean()[0])

In [47]:
df4.describe()

Year     Engine HP
count  11914.000000  11914.000000
mean    2010.384338    259.584902
std        7.579740    172.369994
min     1990.000000     55.000000
25%     2007.000000    170.000000
50%     2015.000000    227.000000
75%     2016.000000    302.000000
max     2017.000000   2010.384338

In [55]:
df5 = df[['Make','Engine HP', 'Engine Cylinders', 'highway MPG']]

In [58]:
df6 = df5[
    df['Make'] == 'Rolls-Royce'
]

In [60]:
df6.drop_duplicates()

Make  Engine HP  Engine Cylinders  highway MPG
2921   Rolls-Royce      325.0               8.0           15
3505   Rolls-Royce      563.0              12.0           19
5275   Rolls-Royce      563.0              12.0           21
5279   Rolls-Royce      563.0              12.0           20
7443   Rolls-Royce      322.0              12.0           15
7553   Rolls-Royce      453.0              12.0           19
11448  Rolls-Royce      624.0              12.0           21

In [61]:
import numpy as np

In [63]:
x = np.array([
    [325, 8, 15],
    [563, 12, 19],
    [563, 12, 21],
    [563, 12, 20],
    [322, 12, 15],
    [453, 12, 19],
    [624, 12, 21]
])

In [81]:
x.T

array([[325, 563, 563, 563, 322, 453, 624],
       [  8,  12,  12,  12,  12,  12,  12],
       [ 15,  19,  21,  20,  15,  19,  21]])

In [84]:
xtx = np.dot(x,x.T)
xtx

array([[105914, 183356, 183386, 183371, 104971, 147606, 203211],
       [183356, 317474, 317512, 317493, 181715, 255544, 351855],
       [183386, 317512, 317554, 317533, 181745, 255582, 351897],
       [183371, 317493, 317533, 317513, 181730, 255563, 351876],
       [104971, 181715, 181745, 181730, 104053, 146295, 201387],
       [147606, 255544, 255582, 255563, 146295, 205714, 283215],
       [203211, 351855, 351897, 351876, 201387, 283215, 389961]])

In [85]:
np.linalg.inv(xtx)

array([[-6.73927593e+10, -1.81692802e+11,  7.48785308e+10,
        -3.18528662e+10,  6.36937052e+10, -2.71582602e+10,
         1.47060199e+11],
       [-6.29137427e+10, -2.05634126e+11,  1.53090219e+11,
        -7.07084718e+10,  1.07044261e+11, -1.11601294e+11,
         1.69751906e+11],
       [ 1.73029720e+10,  1.58501310e+11, -1.59603900e+11,
         4.24365432e+10, -1.19226079e+11,  1.86610143e+11,
        -1.20253331e+11],
       [-4.14754837e+10, -1.11886658e+11,  1.77535361e+11,
        -3.31586119e+09,  7.53459959e+10, -1.33231141e+11,
         2.32026254e+10],
       [-1.37567757e+10,  1.40321201e+10, -8.39304153e+10,
         2.28709419e+10, -4.57426423e+10,  1.04881948e+11,
        -2.94076866e+09],
       [ 9.12254321e+10,  1.28634694e+11,  4.73726118e+10,
        -1.21728564e+10,  2.43575203e+10, -1.50008110e+11,
        -9.90008138e+10],
       [ 5.45461043e+10,  1.37481195e+11, -1.84382897e+11,
         4.21249484e+10, -8.42415259e+10,  1.21453961e+11,
        -6.8799750

In [87]:
xtx.sum()

11671869

In [88]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [89]:
xtxt = np.dot(xtx,x.T)

ValueError: shapes (7,7) and (3,7) not aligned: 7 (dim 1) != 3 (dim 0)